version: '2'
services:
  nesp2_website:
    restart: unless-stopped
    build:
      args:
        POSTGRES_url: ${POSTGRES_URL}
        POSTGRES_user: ${POSTGRES_USER}
        POSTGRES_pw: ${POSTGRES_PW}
        POSTGRES_db: ${POSTGRES_DB}
      context: .
    image: nesp2_website
    container_name: nesp2_website 
    command: gunicorn --bind :80 index:app --workers=2 
    ports:
      - 80:80
  
 # nginx:
  #  build: ./nginx
   # ports:
   #   - 1337:80
   # depends_on:
   #   - nesp2_website 
